version: '2'

services:

  proxy:
    image: nginx:alpine
    name: proxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html/
      - ./data/proxy/certs/:/etc/nginx/certs:ro
    networks:
      - default
      - ambassador
    #lables:
    #  - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  docker-gen:
    image: jwidler/docker-gen
    name: docker-gen
    restart: unless-stopped
    depends_on:
      - proxy
    volumes_from:
      - proxy
    volumes:
      - ./config/docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    #labels:
    #  - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=true"
    command: ["-notify-sighup", "proxy", "-watch", "-wait", "5s:30s", "/etc/docker-gen/templates/nginx.tmpl", "/etc/nginx/conf.d/default.conf"]

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    depends_on:
      - proxy
      - docker-gen
    volumes_from:
      - proxy
    volumes:
      - ./data/proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
      - NGINX_PROXY_CONTAINER=proxy

  sample-app1:
    image: tutum/hello-world
    environment:
      - VIRTUAL_HOST=${sample_app1_vhost}
      - LETSENCRYPT_HOST=${sample_app1_LE_host}
      - LETSENCRYPT_EMAIL=${sample_app1_LE_email}

networks:
  default:
  ambassador:
    external:
      name: ambassador